ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SALES_PERSON';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ACCOUNT_STAFF';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SALES_PERSON_CUM_ACCOUNTS';
