ALTER TYPE "FollowUpStatus" ADD VALUE IF NOT EXISTS 'PARTIAL_PAID';
ALTER TYPE "FollowUpStatus" ADD VALUE IF NOT EXISTS 'WRONG_NUMBER';

ALTER TABLE "FollowUp"
ADD COLUMN IF NOT EXISTS "rescheduledAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "actionLoggedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS "queueRank" INTEGER;

CREATE INDEX IF NOT EXISTS "FollowUp_rescheduledAt_idx" ON "FollowUp"("rescheduledAt");
CREATE INDEX IF NOT EXISTS "FollowUp_queueRank_idx" ON "FollowUp"("queueRank");
