"use client";
import { useEffect, useId, useMemo, useRef, useState } from "react";
import { loadMapplsSdk } from "@/lib/maps/mappls";
import { mapplsOpenUrl } from "@/lib/maps/provider";

type Point={latitude:number;longitude:number;accuracyM?:number|null;heading?:number|null;vehicleName?:string;routeName?:string;lastLocationAt?:string|null};
type MapLike={setCenter?:(position:{lat:number;lng:number}|[number,number])=>void;remove?:()=>void};
type MarkerLike={setPosition?:(position:{lat:number;lng:number})=>void;remove?:()=>void};
type MapplsGlobal={Map:new(id:string,options:Record<string,unknown>)=>MapLike;Marker:new(options:Record<string,unknown>)=>MarkerLike};
function escapeHtml(value:string){return value.replace(/[&<>"]/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[character]??character));}

export function MapplsLiveMap({latitude,longitude,accuracyM,heading,vehicleName,routeName,lastLocationAt,isLive,height="320px",autoCenter=true,locations}:{latitude?:number|null;longitude?:number|null;accuracyM?:number|null;heading?:number|null;vehicleName?:string;routeName?:string;lastLocationAt?:string|null;isLive:boolean;height?:string;autoCenter?:boolean;showAccuracyCircle?:boolean;showPopup?:boolean;locations?:Point[]}){
  const id=`mappls-${useId().replace(/:/g,"")}`; const mapRef=useRef<MapLike|null>(null);const markersRef=useRef<MarkerLike[]>([]);const [error,setError]=useState("");
  const points=useMemo(()=>locations?.length?locations:latitude!=null&&longitude!=null?[{latitude,longitude,accuracyM,heading,vehicleName,routeName,lastLocationAt}]:[],[locations,latitude,longitude,accuracyM,heading,vehicleName,routeName,lastLocationAt]);
  useEffect(()=>{const key=process.env.NEXT_PUBLIC_MAPPLS_MAP_SDK_KEY;if(!key||!points.length)return;let cancelled=false;loadMapplsSdk(key).then(()=>{if(cancelled)return;const sdk=(window as Window&{mappls?:MapplsGlobal}).mappls;if(!sdk)throw new Error("Mappls SDK unavailable.");const first=points[0];if(!mapRef.current)mapRef.current=new sdk.Map(id,{center:[first.latitude,first.longitude],zoom:15});markersRef.current.forEach(m=>m.remove?.());markersRef.current=points.map(point=>new sdk.Marker({map:mapRef.current,position:{lat:point.latitude,lng:point.longitude},icon_url:"/icons/school-van-marker.svg",width:44,height:44,rotation:point.heading??0,fitbounds:points.length>1,popupHtml:`<strong>${escapeHtml(point.vehicleName??"School Van")}</strong><br/>${escapeHtml(point.routeName??"")}`}));if(autoCenter)mapRef.current.setCenter?.({lat:first.latitude,lng:first.longitude});setError("");}).catch(()=>setError("Map could not load. Last location is available below."));return()=>{cancelled=true};},[id,autoCenter,points]);
  if(!points.length)return <div className="flex items-center justify-center rounded-xl border bg-slate-50 text-sm text-slate-500 dark:border-slate-800 dark:bg-slate-900" style={{height}}>Location not available yet</div>;
  const first=points[0];const missing=!process.env.NEXT_PUBLIC_MAPPLS_MAP_SDK_KEY;
  return <div className="space-y-2"><div className="relative overflow-hidden rounded-xl border dark:border-slate-800" style={{height}}><div id={id} className="h-full w-full" />{(missing||error)&&<div className="absolute inset-0 flex flex-col items-center justify-center bg-slate-100/95 p-4 text-center text-sm dark:bg-slate-900/95"><p>{missing?"Mappls map key is not configured.":error}</p><p className="mt-2 font-mono text-xs">{first.latitude.toFixed(6)}, {first.longitude.toFixed(6)}</p></div>}{!isLive&&<span className="absolute right-2 top-2 rounded-full bg-slate-700 px-2 py-1 text-xs font-bold text-white">Stale</span>}</div><a href={mapplsOpenUrl(first.latitude,first.longitude)} target="_blank" rel="noreferrer" className="inline-flex text-xs font-semibold text-brand-700">Open in Mappls</a></div>;
}
