"use client";
import{useCallback,useEffect,useRef,useState}from"react";import{Loader2,MapPin,Play,Square}from"lucide-react";import{MapplsLiveMap}from"@/components/maps/MapplsLiveMap";
type Option={id:string;name:string;vehicleNumber?:string|null};type Route={id:string;name:string};type Trip={id:string;status:string;vehicle:Option;route:Route|null;lastLatitude:number|null;lastLongitude:number|null;lastAccuracyM:number|null;lastHeading:number|null;lastLocationAt:string|null};type Data={vehicles:Option[];routes:Route[];activeTrip:Trip|null};type QueuedPoint={latitude:number;longitude:number;accuracyM:number|null;speedKmph:number|null;heading:number|null;recordedAt:string};
const QUEUE="school-trip-location-queue";function point(p:GeolocationPosition):QueuedPoint{return{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracyM:p.coords.accuracy,speedKmph:p.coords.speed==null?null:p.coords.speed*3.6,heading:p.coords.heading,recordedAt:new Date(p.timestamp).toISOString()}}
export default function SchoolDriverPage(){const[data,setData]=useState<Data|null>(null),[vehicleId,setVehicleId]=useState(""),[routeId,setRouteId]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[gps,setGps]=useState("Permission not requested"),[online,setOnline]=useState(true);const watch=useRef<number|null>(null),lastSent=useRef(0),wake=useRef<{release:()=>Promise<void>}|null>(null);const activeTripId=data?.activeTrip?.id;const activeTripIdRef=useRef<string|undefined>(activeTripId);activeTripIdRef.current=activeTripId;
const load=useCallback(async()=>{const r=await fetch("/api/school-transport/driver/options",{cache:"no-store"});const j=await r.json().catch(()=>({}));if(r.ok){setData(j);setVehicleId(v=>v||j.vehicles?.[0]?.id||"");setRouteId(v=>v||j.routes?.[0]?.id||"")}else setMessage(j.error??"Could not load trip options.")},[]);
const send=useCallback(async(tripId:string,p:QueuedPoint)=>{const r=await fetch(`/api/school-transport/trips/${tripId}/location`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});if(!r.ok)throw new Error("Location send failed");setGps(`GPS active · ${Math.round(p.accuracyM??0)}m · ${new Date().toLocaleTimeString()}`);await load()},[load]);
const flush=useCallback(async(tripId:string)=>{const q:QueuedPoint[]=JSON.parse(localStorage.getItem(QUEUE)||"[]");const left:QueuedPoint[]=[];for(const p of q){try{await send(tripId,p)}catch{left.push(p)}}localStorage.setItem(QUEUE,JSON.stringify(left.slice(-50)))},[send]);
const startWatch=useCallback((tripId:string)=>{if(!navigator.geolocation)return;watch.current=navigator.geolocation.watchPosition(p=>{const now=Date.now();if(now-lastSent.current<10000)return;lastSent.current=now;const payload=point(p);void send(tripId,payload).catch(()=>{const q=JSON.parse(localStorage.getItem(QUEUE)||"[]");localStorage.setItem(QUEUE,JSON.stringify([...q,payload].slice(-50)));setMessage("Offline: location saved for retry.")})},e=>setGps(e.code===1?"Location permission denied":e.message),{enableHighAccuracy:true,maximumAge:3000,timeout:15000})},[send]);
const stopWatch=useCallback(()=>{if(watch.current!=null)navigator.geolocation.clearWatch(watch.current);watch.current=null;void wake.current?.release().catch(()=>undefined);wake.current=null},[]);
async function start(){if(!vehicleId||busy)return;setBusy(true);setMessage("");navigator.geolocation.getCurrentPosition(async p=>{const r=await fetch("/api/school-transport/trips/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({vehicleId,routeId:routeId||null})});const j=await r.json().catch(()=>({}));if(!r.ok){setMessage(j.error??"Could not start trip.");setBusy(false);return}const nav=navigator as Navigator&{wakeLock?:{request:(type:"screen")=>Promise<{release:()=>Promise<void>}>}};wake.current=await nav.wakeLock?.request("screen").catch(()=>null)??null;await send(j.trip.id,point(p)).catch(()=>undefined);startWatch(j.trip.id);await load();setBusy(false)},e=>{setGps(e.code===1?"Location permission denied":e.message);setBusy(false)},{enableHighAccuracy:true,maximumAge:0,timeout:15000})}
async function end(){const trip=data?.activeTrip;if(!trip||busy)return;setBusy(true);stopWatch();const r=await fetch(`/api/school-transport/trips/${trip.id}/end`,{method:"POST"});const j=await r.json().catch(()=>({}));setMessage(r.ok?"Trip completed.":j.error??"Could not end trip.");await load();setBusy(false)}
useEffect(()=>{setOnline(navigator.onLine);void load();const on=()=>{setOnline(navigator.onLine);if(navigator.onLine&&activeTripIdRef.current)void flush(activeTripIdRef.current)};addEventListener("online",on);addEventListener("offline",on);return()=>{removeEventListener("online",on);removeEventListener("offline",on);stopWatch()}},[load,flush,stopWatch]);useEffect(()=>{if(activeTripId&&watch.current==null)startWatch(activeTripId)},[activeTripId,startWatch]);const trip=data?.activeTrip;
return <div className="mx-auto max-w-xl space-y-4 pb-24"><div><p className="text-xs font-bold uppercase text-brand-600">School Driver</p><h1 className="text-2xl font-bold">My School Trip</h1><p className="text-sm text-slate-500">Live tracking works while this screen is open. Keep phone unlocked or allow screen to stay active during trip.</p></div>{!online&&<div className="rounded-lg bg-amber-100 p-3 text-sm font-bold text-amber-800">Offline · GPS points will retry when online.</div>}{message&&<div className="rounded-lg border p-3 text-sm">{message}</div>}<section className="space-y-3 rounded-xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><label className="text-sm font-semibold">Assigned vehicle</label><select disabled={!!trip} value={vehicleId} onChange={e=>setVehicleId(e.target.value)} className="min-h-11 w-full rounded-lg border px-3">{data?.vehicles.map(v=><option key={v.id} value={v.id}>{v.name} {v.vehicleNumber}</option>)}</select><label className="text-sm font-semibold">Route</label><select disabled={!!trip} value={routeId} onChange={e=>setRouteId(e.target.value)} className="min-h-11 w-full rounded-lg border px-3"><option value="">No route</option>{data?.routes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><p className="text-sm"><MapPin className="mr-1 inline h-4 w-4"/>{gps}</p><p className="text-sm font-bold">Status: {trip?"RUNNING":"NOT STARTED"}</p></section>{trip&&<MapplsLiveMap latitude={trip.lastLatitude} longitude={trip.lastLongitude} accuracyM={trip.lastAccuracyM} heading={trip.lastHeading} vehicleName={trip.vehicle.name} routeName={trip.route?.name} lastLocationAt={trip.lastLocationAt} isLive height="300px"/>}<div className="grid grid-cols-2 gap-3"><button disabled={busy||!!trip||!vehicleId} onClick={()=>void start()} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-emerald-600 font-bold text-white disabled:opacity-50">{busy?<Loader2 className="h-5 w-5 animate-spin"/>:<Play className="h-5 w-5"/>}Start School Trip</button><button disabled={busy||!trip} onClick={()=>void end()} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-red-600 font-bold text-white disabled:opacity-50"><Square className="h-5 w-5"/>End Trip</button></div><p className="rounded-lg bg-blue-50 p-3 text-sm font-semibold text-blue-800">Keep this screen open for live tracking.</p></div>}
